### ISSUE TITLE
Resolving Relative References

### ISSUE THREAD

**Issue by natebrunette** [thephpleague/json-reference#6]
Is it possible to use relative references (e.g. `./path/to/file.yaml#/Foo`)?

It looks like the dereferencer `\League\JsonReference\Dereferencer` checks for an internal reference on line 69 and passes null if it's not internal.

**Comment by matt-allan** [comment]
Hello,

Relative references should work.

It gets kind of confusing with JSON Schema because of `id`.  There are docs [here](http://json-guard.thephpleague.com/json-reference/scope-resolution).

The code on line 69 is an optimization for internal references (relative and in the same schema).  If we know it's an internal reference then we already have the schema that is being referenced so we keep it in memory instead of loading it again later.

**Comment by natebrunette** [comment]
@yuloh Thanks, can you point me to a test that demonstrates this working? I can't wrap my head around the documentation.

**Comment by matt-allan** [comment]
[This test](https://github.com/thephpleague/json-reference/blob/master/tests/DereferencerTest.php#L47) covers relative resolution.

[This PR](https://github.com/json-schema-org/JSON-Schema-Test-Suite/pull/123) added a similar test to the official JSON Schema test suite but it was reverted for an unrelated reason.

There are some extra tests in the json-guard repo that cover the JSON Schema specific ID resolution but I haven't ported those over yet.

I will try and put together some examples and better docs when I get a chance.

Lets say you have this schema:

```
{
  "type": "array",
  "items": {
    "$ref": "./album.json"
  }
}
```

If you initially load the schema like `$dereferencer->dereference('http://my.app/albums.json')`, it's going to try to load `http://my.app/album.json` when it encounters the reference.

If you load it as file, i.e. `$dereferencer->dereference('file://some/path/albums.json')` it will look for `file://some/path/album.json`.

If you loaded the schema as an object, i.e. `$dereferencer->dereference(json_decode(__DIR__ . '/albums.json')))` it will throw an exception because the file does not have an id (explained below) and it doesn't know what to use as the base for resolving a relative url.

If you had this schema:

```
{
  "id": "http://my.app/albums.json"
  "type": "array",
  "items": {
    "$ref": "./album.json"
  }
}
```

...and you created the Dereferencer with the JSON Schema Draft 4 Scope Resolver (`Dereferencer::draft4()`), then it will **always** look for `http://my.app/album.json`, even if you initially loaded the schema from the local filesystem ([explained here](https://spacetelescope.github.io/understanding-json-schema/structuring.html#the-id-property) and [here](https://github.com/json-schema/json-schema/wiki/The-id-keyword)).

If you are doing development locally you probably don't want to resolve against the id and do a HTTP request every time.  The default constructor when you call `new Dereferencer()` will always use the path it was loaded from and ignore the id.

Hopefully that helps.

**Comment by natebrunette** [comment]
@yuloh Thanks for the lengthy description. I think part of my problem is that our schema is in yaml. It looks like the library doesn't currently support yaml; is that something you'd be open to adding? If so, I could try to put together a PR.

EDIT: Actually, it looks like I can just create a yaml file loader. I'm going to go down that path, thanks for the help.
